package com.springboot.c4_domain.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.stereotype.Repository;

import java.util.Date;

@Data
@Repository
public class AdminChat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_chat.admin_chat_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer adminChatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_chat.time
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    @JsonFormat(timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_chat.content
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private String content;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_chat.admin_chat_id
     *
     * @return the value of admin_chat.admin_chat_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getAdminChatId() {
        return adminChatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_chat.admin_chat_id
     *
     * @param adminChatId the value for admin_chat.admin_chat_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setAdminChatId(Integer adminChatId) {
        this.adminChatId = adminChatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_chat.time
     *
     * @return the value of admin_chat.time
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_chat.time
     *
     * @param time the value for admin_chat.time
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_chat.content
     *
     * @return the value of admin_chat.content
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_chat.content
     *
     * @param content the value for admin_chat.content
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}