package com.springboot.c4_domain.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.stereotype.Repository;

import java.util.Date;

@Data
@Repository
public class Roast {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roast.roast_id
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    private Integer roastId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roast.time
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    @JsonFormat(timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roast.applause_number
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    private Integer applauseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roast.is_deleted
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roast.content
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    private String content;

    public Roast() {
    }

    public Roast(Date time, Integer applauseNumber, String content) {
        this.time = time;
        this.applauseNumber = applauseNumber;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roast.roast_id
     *
     * @return the value of roast.roast_id
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    public Integer getRoastId() {
        return roastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roast.roast_id
     *
     * @param roastId the value for roast.roast_id
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    public void setRoastId(Integer roastId) {
        this.roastId = roastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roast.time
     *
     * @return the value of roast.time
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roast.time
     *
     * @param time the value for roast.time
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roast.applause_number
     *
     * @return the value of roast.applause_number
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    public Integer getApplauseNumber() {
        return applauseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roast.applause_number
     *
     * @param applauseNumber the value for roast.applause_number
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    public void setApplauseNumber(Integer applauseNumber) {
        this.applauseNumber = applauseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roast.is_deleted
     *
     * @return the value of roast.is_deleted
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roast.is_deleted
     *
     * @param isDeleted the value for roast.is_deleted
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roast.content
     *
     * @return the value of roast.content
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roast.content
     *
     * @param content the value for roast.content
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}