package com.springboot.c4_domain.entity;

public class UserRoast {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roast.user_roast_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer userRoastId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roast.user_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roast.roast_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer roastId;

    public UserRoast() {
    }

    public UserRoast(Integer userId, Integer roastId) {
        this.userId = userId;
        this.roastId = roastId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roast.user_roast_id
     *
     * @return the value of user_roast.user_roast_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getUserRoastId() {
        return userRoastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roast.user_roast_id
     *
     * @param userRoastId the value for user_roast.user_roast_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setUserRoastId(Integer userRoastId) {
        this.userRoastId = userRoastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roast.user_id
     *
     * @return the value of user_roast.user_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roast.user_id
     *
     * @param userId the value for user_roast.user_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roast.roast_id
     *
     * @return the value of user_roast.roast_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getRoastId() {
        return roastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roast.roast_id
     *
     * @param roastId the value for user_roast.roast_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setRoastId(Integer roastId) {
        this.roastId = roastId;
    }
}