package com.springboot.c4_domain.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class UserChat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat.user_chat_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer userChatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat.time
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    @JsonFormat(timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat.content
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private String content;

    public UserChat() {
    }

    public UserChat(String content,Date time) {
        this.time = time;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat.user_chat_id
     *
     * @return the value of user_chat.user_chat_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getUserChatId() {
        return userChatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat.user_chat_id
     *
     * @param userChatId the value for user_chat.user_chat_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setUserChatId(Integer userChatId) {
        this.userChatId = userChatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat.time
     *
     * @return the value of user_chat.time
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat.time
     *
     * @param time the value for user_chat.time
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat.content
     *
     * @return the value of user_chat.content
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat.content
     *
     * @param content the value for user_chat.content
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}