package com.springboot.c4_domain.entity;

import lombok.Data;
import org.springframework.stereotype.Repository;

@Data
@Repository
public class UserRoastComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roast_comment.user_roast_comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer userRoastCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roast_comment.user_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roast_comment.comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roast_comment.roast_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer roastId;

    public UserRoastComment() {
    }

    public UserRoastComment(Integer userId,  Integer roastId, Integer commentId) {
        this.userId = userId;
        this.roastId = roastId;
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roast_comment.user_roast_comment_id
     *
     * @return the value of user_roast_comment.user_roast_comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getUserRoastCommentId() {
        return userRoastCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roast_comment.user_roast_comment_id
     *
     * @param userRoastCommentId the value for user_roast_comment.user_roast_comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setUserRoastCommentId(Integer userRoastCommentId) {
        this.userRoastCommentId = userRoastCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roast_comment.user_id
     *
     * @return the value of user_roast_comment.user_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roast_comment.user_id
     *
     * @param userId the value for user_roast_comment.user_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roast_comment.comment_id
     *
     * @return the value of user_roast_comment.comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roast_comment.comment_id
     *
     * @param commentId the value for user_roast_comment.comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roast_comment.roast_id
     *
     * @return the value of user_roast_comment.roast_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getRoastId() {
        return roastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roast_comment.roast_id
     *
     * @param roastId the value for user_roast_comment.roast_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setRoastId(Integer roastId) {
        this.roastId = roastId;
    }
}