package com.springboot.c4_domain.entity;

public class UserWish {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wish.user_wish_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer userWishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wish.user_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wish.wish_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer wishId;

    public UserWish() {
    }

    public UserWish(Integer userId, Integer wishId) {
        this.userId = userId;
        this.wishId = wishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wish.user_wish_id
     *
     * @return the value of user_wish.user_wish_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getUserWishId() {
        return userWishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wish.user_wish_id
     *
     * @param userWishId the value for user_wish.user_wish_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setUserWishId(Integer userWishId) {
        this.userWishId = userWishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wish.user_id
     *
     * @return the value of user_wish.user_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wish.user_id
     *
     * @param userId the value for user_wish.user_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wish.wish_id
     *
     * @return the value of user_wish.wish_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getWishId() {
        return wishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wish.wish_id
     *
     * @param wishId the value for user_wish.wish_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setWishId(Integer wishId) {
        this.wishId = wishId;
    }
}