package com.springboot.c4_domain.entity;

import java.util.ArrayList;
import java.util.List;

public class UserChatRelationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public UserChatRelationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserChatRelationIdIsNull() {
            addCriterion("user_chat_relation_id is null");
            return (Criteria) this;
        }

        public Criteria andUserChatRelationIdIsNotNull() {
            addCriterion("user_chat_relation_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserChatRelationIdEqualTo(Integer value) {
            addCriterion("user_chat_relation_id =", value, "userChatRelationId");
            return (Criteria) this;
        }

        public Criteria andUserChatRelationIdNotEqualTo(Integer value) {
            addCriterion("user_chat_relation_id <>", value, "userChatRelationId");
            return (Criteria) this;
        }

        public Criteria andUserChatRelationIdGreaterThan(Integer value) {
            addCriterion("user_chat_relation_id >", value, "userChatRelationId");
            return (Criteria) this;
        }

        public Criteria andUserChatRelationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_chat_relation_id >=", value, "userChatRelationId");
            return (Criteria) this;
        }

        public Criteria andUserChatRelationIdLessThan(Integer value) {
            addCriterion("user_chat_relation_id <", value, "userChatRelationId");
            return (Criteria) this;
        }

        public Criteria andUserChatRelationIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_chat_relation_id <=", value, "userChatRelationId");
            return (Criteria) this;
        }

        public Criteria andUserChatRelationIdIn(List<Integer> values) {
            addCriterion("user_chat_relation_id in", values, "userChatRelationId");
            return (Criteria) this;
        }

        public Criteria andUserChatRelationIdNotIn(List<Integer> values) {
            addCriterion("user_chat_relation_id not in", values, "userChatRelationId");
            return (Criteria) this;
        }

        public Criteria andUserChatRelationIdBetween(Integer value1, Integer value2) {
            addCriterion("user_chat_relation_id between", value1, value2, "userChatRelationId");
            return (Criteria) this;
        }

        public Criteria andUserChatRelationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_chat_relation_id not between", value1, value2, "userChatRelationId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserChatIdIsNull() {
            addCriterion("user_chat_id is null");
            return (Criteria) this;
        }

        public Criteria andUserChatIdIsNotNull() {
            addCriterion("user_chat_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserChatIdEqualTo(Integer value) {
            addCriterion("user_chat_id =", value, "userChatId");
            return (Criteria) this;
        }

        public Criteria andUserChatIdNotEqualTo(Integer value) {
            addCriterion("user_chat_id <>", value, "userChatId");
            return (Criteria) this;
        }

        public Criteria andUserChatIdGreaterThan(Integer value) {
            addCriterion("user_chat_id >", value, "userChatId");
            return (Criteria) this;
        }

        public Criteria andUserChatIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_chat_id >=", value, "userChatId");
            return (Criteria) this;
        }

        public Criteria andUserChatIdLessThan(Integer value) {
            addCriterion("user_chat_id <", value, "userChatId");
            return (Criteria) this;
        }

        public Criteria andUserChatIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_chat_id <=", value, "userChatId");
            return (Criteria) this;
        }

        public Criteria andUserChatIdIn(List<Integer> values) {
            addCriterion("user_chat_id in", values, "userChatId");
            return (Criteria) this;
        }

        public Criteria andUserChatIdNotIn(List<Integer> values) {
            addCriterion("user_chat_id not in", values, "userChatId");
            return (Criteria) this;
        }

        public Criteria andUserChatIdBetween(Integer value1, Integer value2) {
            addCriterion("user_chat_id between", value1, value2, "userChatId");
            return (Criteria) this;
        }

        public Criteria andUserChatIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_chat_id not between", value1, value2, "userChatId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_chat_relation
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 08 11:49:11 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}