package com.springboot.c4_domain.entity;

import lombok.Data;
import org.springframework.stereotype.Repository;

@Data
@Repository
public class UserWishComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wish_comment.user_wish_comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer userWishCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wish_comment.user_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wish_comment.comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wish_comment.wish_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer wishId;

    public UserWishComment() {
    }

    public UserWishComment(Integer userId, Integer wishId, Integer commentId) {
        this.userId = userId;
        this.wishId = wishId;
        this.commentId = commentId;

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wish_comment.user_wish_comment_id
     *
     * @return the value of user_wish_comment.user_wish_comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getUserWishCommentId() {
        return userWishCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wish_comment.user_wish_comment_id
     *
     * @param userWishCommentId the value for user_wish_comment.user_wish_comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setUserWishCommentId(Integer userWishCommentId) {
        this.userWishCommentId = userWishCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wish_comment.user_id
     *
     * @return the value of user_wish_comment.user_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wish_comment.user_id
     *
     * @param userId the value for user_wish_comment.user_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wish_comment.comment_id
     *
     * @return the value of user_wish_comment.comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wish_comment.comment_id
     *
     * @param commentId the value for user_wish_comment.comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wish_comment.wish_id
     *
     * @return the value of user_wish_comment.wish_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getWishId() {
        return wishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wish_comment.wish_id
     *
     * @param wishId the value for user_wish_comment.wish_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setWishId(Integer wishId) {
        this.wishId = wishId;
    }
}