package com.springboot.c4_domain.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.stereotype.Repository;

import java.util.Date;

@Data
@Repository
public class WishComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wish_comment.wish_comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer wishCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wish_comment.time
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    @JsonFormat(timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wish_comment.content
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private String content;

    public WishComment() {
    }

    public WishComment(Date time, String content) {
        this.time = time;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wish_comment.wish_comment_id
     *
     * @return the value of wish_comment.wish_comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */


    public Integer getWishCommentId() {
        return wishCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wish_comment.wish_comment_id
     *
     * @param wishCommentId the value for wish_comment.wish_comment_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setWishCommentId(Integer wishCommentId) {
        this.wishCommentId = wishCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wish_comment.time
     *
     * @return the value of wish_comment.time
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wish_comment.time
     *
     * @param time the value for wish_comment.time
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wish_comment.content
     *
     * @return the value of wish_comment.content
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wish_comment.content
     *
     * @param content the value for wish_comment.content
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}