package com.springboot.c4_domain.entity;


import lombok.Data;
import org.springframework.stereotype.Repository;

@Data
@Repository
public class AdminChatRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_chat_relation.admin_chat_relation_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer adminChatRelationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_chat_relation.admin_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_chat_relation.admin_chat_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    private Integer adminChatId;

    public AdminChatRelation() {
    }

    public AdminChatRelation(Integer adminId, Integer adminChatId) {
        this.adminId = adminId;
        this.adminChatId = adminChatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_chat_relation.admin_chat_relation_id
     *
     * @return the value of admin_chat_relation.admin_chat_relation_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getAdminChatRelationId() {
        return adminChatRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_chat_relation.admin_chat_relation_id
     *
     * @param adminChatRelationId the value for admin_chat_relation.admin_chat_relation_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setAdminChatRelationId(Integer adminChatRelationId) {
        this.adminChatRelationId = adminChatRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_chat_relation.admin_id
     *
     * @return the value of admin_chat_relation.admin_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_chat_relation.admin_id
     *
     * @param adminId the value for admin_chat_relation.admin_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_chat_relation.admin_chat_id
     *
     * @return the value of admin_chat_relation.admin_chat_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Integer getAdminChatId() {
        return adminChatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_chat_relation.admin_chat_id
     *
     * @param adminChatId the value for admin_chat_relation.admin_chat_id
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setAdminChatId(Integer adminChatId) {
        this.adminChatId = adminChatId;
    }
}