package com.springboot.c4_domain.entity;

import java.util.ArrayList;
import java.util.List;

public class UserRoastExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public UserRoastExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserRoastIdIsNull() {
            addCriterion("user_roast_id is null");
            return (Criteria) this;
        }

        public Criteria andUserRoastIdIsNotNull() {
            addCriterion("user_roast_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserRoastIdEqualTo(Integer value) {
            addCriterion("user_roast_id =", value, "userRoastId");
            return (Criteria) this;
        }

        public Criteria andUserRoastIdNotEqualTo(Integer value) {
            addCriterion("user_roast_id <>", value, "userRoastId");
            return (Criteria) this;
        }

        public Criteria andUserRoastIdGreaterThan(Integer value) {
            addCriterion("user_roast_id >", value, "userRoastId");
            return (Criteria) this;
        }

        public Criteria andUserRoastIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_roast_id >=", value, "userRoastId");
            return (Criteria) this;
        }

        public Criteria andUserRoastIdLessThan(Integer value) {
            addCriterion("user_roast_id <", value, "userRoastId");
            return (Criteria) this;
        }

        public Criteria andUserRoastIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_roast_id <=", value, "userRoastId");
            return (Criteria) this;
        }

        public Criteria andUserRoastIdIn(List<Integer> values) {
            addCriterion("user_roast_id in", values, "userRoastId");
            return (Criteria) this;
        }

        public Criteria andUserRoastIdNotIn(List<Integer> values) {
            addCriterion("user_roast_id not in", values, "userRoastId");
            return (Criteria) this;
        }

        public Criteria andUserRoastIdBetween(Integer value1, Integer value2) {
            addCriterion("user_roast_id between", value1, value2, "userRoastId");
            return (Criteria) this;
        }

        public Criteria andUserRoastIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_roast_id not between", value1, value2, "userRoastId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRoastIdIsNull() {
            addCriterion("roast_id is null");
            return (Criteria) this;
        }

        public Criteria andRoastIdIsNotNull() {
            addCriterion("roast_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoastIdEqualTo(Integer value) {
            addCriterion("roast_id =", value, "roastId");
            return (Criteria) this;
        }

        public Criteria andRoastIdNotEqualTo(Integer value) {
            addCriterion("roast_id <>", value, "roastId");
            return (Criteria) this;
        }

        public Criteria andRoastIdGreaterThan(Integer value) {
            addCriterion("roast_id >", value, "roastId");
            return (Criteria) this;
        }

        public Criteria andRoastIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("roast_id >=", value, "roastId");
            return (Criteria) this;
        }

        public Criteria andRoastIdLessThan(Integer value) {
            addCriterion("roast_id <", value, "roastId");
            return (Criteria) this;
        }

        public Criteria andRoastIdLessThanOrEqualTo(Integer value) {
            addCriterion("roast_id <=", value, "roastId");
            return (Criteria) this;
        }

        public Criteria andRoastIdIn(List<Integer> values) {
            addCriterion("roast_id in", values, "roastId");
            return (Criteria) this;
        }

        public Criteria andRoastIdNotIn(List<Integer> values) {
            addCriterion("roast_id not in", values, "roastId");
            return (Criteria) this;
        }

        public Criteria andRoastIdBetween(Integer value1, Integer value2) {
            addCriterion("roast_id between", value1, value2, "roastId");
            return (Criteria) this;
        }

        public Criteria andRoastIdNotBetween(Integer value1, Integer value2) {
            addCriterion("roast_id not between", value1, value2, "roastId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_roast
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 08 11:49:11 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_roast
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}