package com.springboot.c3_dao;

import com.springboot.c4_domain.entity.AdminChat;
import com.springboot.c4_domain.entity.AdminChatExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AdminChatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int countByExample(AdminChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int deleteByExample(AdminChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int deleteByPrimaryKey(Integer adminChatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int insert(AdminChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int insertSelective(AdminChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    List<AdminChat> selectByExampleWithBLOBs(AdminChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    List<AdminChat> selectByExample(AdminChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    AdminChat selectByPrimaryKey(Integer adminChatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExampleSelective(@Param("record") AdminChat record, @Param("example") AdminChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") AdminChat record, @Param("example") AdminChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExample(@Param("record") AdminChat record, @Param("example") AdminChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKeySelective(AdminChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(AdminChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKey(AdminChat record);
}