package com.springboot.c3_dao;

import com.springboot.c4_domain.entity.AdminChatRelation;
import com.springboot.c4_domain.entity.AdminChatRelationExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AdminChatRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int countByExample(AdminChatRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int deleteByExample(AdminChatRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int deleteByPrimaryKey(Integer adminChatRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int insert(AdminChatRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int insertSelective(AdminChatRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    List<AdminChatRelation> selectByExample(AdminChatRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    AdminChatRelation selectByPrimaryKey(Integer adminChatRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExampleSelective(@Param("record") AdminChatRelation record, @Param("example") AdminChatRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExample(@Param("record") AdminChatRelation record, @Param("example") AdminChatRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKeySelective(AdminChatRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKey(AdminChatRelation record);
}