package com.springboot.c3_dao;

import com.springboot.c4_domain.entity.Roast;
import com.springboot.c4_domain.entity.RoastExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RoastMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int countByExample(RoastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int deleteByExample(RoastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int deleteByPrimaryKey(Integer roastId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int insert(Roast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int insertSelective(Roast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    List<Roast> selectByExampleWithBLOBs(RoastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    List<Roast> selectByExample(RoastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    Roast selectByPrimaryKey(Integer roastId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int updateByExampleSelective(@Param("record") Roast record, @Param("example") RoastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") Roast record, @Param("example") RoastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int updateByExample(@Param("record") Roast record, @Param("example") RoastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int updateByPrimaryKeySelective(Roast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(Roast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int updateByPrimaryKey(Roast record);
}