package com.springboot.c3_dao;

import com.springboot.c4_domain.entity.UserRoastComment;
import com.springboot.c4_domain.entity.UserRoastCommentExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserRoastCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int countByExample(UserRoastCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int deleteByExample(UserRoastCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int deleteByPrimaryKey(Integer userRoastCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int insert(UserRoastComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int insertSelective(UserRoastComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    List<UserRoastComment> selectByExample(UserRoastCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    UserRoastComment selectByPrimaryKey(Integer userRoastCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExampleSelective(@Param("record") UserRoastComment record, @Param("example") UserRoastCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExample(@Param("record") UserRoastComment record, @Param("example") UserRoastCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKeySelective(UserRoastComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roast_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKey(UserRoastComment record);
}