package com.springboot.c3_dao;

import com.springboot.c4_domain.entity.UserWish;
import com.springboot.c4_domain.entity.UserWishExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserWishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wish
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int countByExample(UserWishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wish
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int deleteByExample(UserWishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wish
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int deleteByPrimaryKey(Integer userWishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wish
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int insert(UserWish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wish
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int insertSelective(UserWish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wish
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    List<UserWish> selectByExample(UserWishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wish
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    UserWish selectByPrimaryKey(Integer userWishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wish
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExampleSelective(@Param("record") UserWish record, @Param("example") UserWishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wish
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExample(@Param("record") UserWish record, @Param("example") UserWishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wish
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKeySelective(UserWish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wish
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKey(UserWish record);
}