package com.springboot.c3_dao;

import com.springboot.c4_domain.entity.UserChatRelation;
import com.springboot.c4_domain.entity.UserChatRelationExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserChatRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int countByExample(UserChatRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int deleteByExample(UserChatRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int deleteByPrimaryKey(Integer userChatRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int insert(UserChatRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int insertSelective(UserChatRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    List<UserChatRelation> selectByExample(UserChatRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    UserChatRelation selectByPrimaryKey(Integer userChatRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExampleSelective(@Param("record") UserChatRelation record, @Param("example") UserChatRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExample(@Param("record") UserChatRelation record, @Param("example") UserChatRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKeySelective(UserChatRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chat_relation
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKey(UserChatRelation record);
}