package com.springboot.c3_dao;

import com.springboot.c4_domain.entity.Wish;
import com.springboot.c4_domain.entity.WishExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface WishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    int countByExample(WishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    int deleteByExample(WishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    int deleteByPrimaryKey(Integer wishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    int insert(Wish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    int insertSelective(Wish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    List<Wish> selectByExampleWithBLOBs(WishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    List<Wish> selectByExample(WishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    Wish selectByPrimaryKey(Integer wishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    int updateByExampleSelective(@Param("record") Wish record, @Param("example") WishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") Wish record, @Param("example") WishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    int updateByExample(@Param("record") Wish record, @Param("example") WishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    int updateByPrimaryKeySelective(Wish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(Wish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    int updateByPrimaryKey(Wish record);
}