package com.springboot.c3_dao;

import com.springboot.c4_domain.entity.WishComment;
import com.springboot.c4_domain.entity.WishCommentExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface WishCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int countByExample(WishCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int deleteByExample(WishCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int deleteByPrimaryKey(Integer wishCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int insert(WishComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int insertSelective(WishComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    List<WishComment> selectByExampleWithBLOBs(WishCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    List<WishComment> selectByExample(WishCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    WishComment selectByPrimaryKey(Integer wishCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExampleSelective(@Param("record") WishComment record, @Param("example") WishCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") WishComment record, @Param("example") WishCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByExample(@Param("record") WishComment record, @Param("example") WishCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKeySelective(WishComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(WishComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wish_comment
     *
     * @mbggenerated Fri Mar 08 11:49:11 CST 2024
     */
    int updateByPrimaryKey(WishComment record);
}