package com.springboot.c3_dao;

import com.springboot.c4_domain.entity.RoastComment;
import com.springboot.c4_domain.entity.RoastCommentExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RoastCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int countByExample(RoastCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int deleteByExample(RoastCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int deleteByPrimaryKey(Integer roastCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int insert(RoastComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int insertSelective(RoastComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    List<RoastComment> selectByExampleWithBLOBs(RoastCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    List<RoastComment> selectByExample(RoastCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    RoastComment selectByPrimaryKey(Integer roastCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int updateByExampleSelective(@Param("record") RoastComment record, @Param("example") RoastCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") RoastComment record, @Param("example") RoastCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int updateByExample(@Param("record") RoastComment record, @Param("example") RoastCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int updateByPrimaryKeySelective(RoastComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(RoastComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roast_comment
     *
     * @mbggenerated Mon Mar 18 22:37:41 CST 2024
     */
    int updateByPrimaryKey(RoastComment record);
}