package com.springboot.c4_domain.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.stereotype.Repository;

import java.util.Date;

@Data
@Repository
public class Wish {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wish.wish_id
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    private Integer wishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wish.time
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    @JsonFormat(timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wish.applause_number
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    private Integer applauseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wish.is_deleted
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wish.content
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    private String content;

    public Wish() {
    }

    public Wish(Date time, Integer applauseNumber, String content) {
        this.time = time;
        this.applauseNumber = applauseNumber;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wish.wish_id
     *
     * @return the value of wish.wish_id
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    public Integer getWishId() {
        return wishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wish.wish_id
     *
     * @param wishId the value for wish.wish_id
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    public void setWishId(Integer wishId) {
        this.wishId = wishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wish.time
     *
     * @return the value of wish.time
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wish.time
     *
     * @param time the value for wish.time
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wish.applause_number
     *
     * @return the value of wish.applause_number
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    public Integer getApplauseNumber() {
        return applauseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wish.applause_number
     *
     * @param applauseNumber the value for wish.applause_number
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    public void setApplauseNumber(Integer applauseNumber) {
        this.applauseNumber = applauseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wish.is_deleted
     *
     * @return the value of wish.is_deleted
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wish.is_deleted
     *
     * @param isDeleted the value for wish.is_deleted
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wish.content
     *
     * @return the value of wish.content
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wish.content
     *
     * @param content the value for wish.content
     *
     * @mbggenerated Mon Mar 18 23:10:49 CST 2024
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}